<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Bank::create(['code' => '3', 'name' => 'BANK EKSPOR INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '8', 'name' => 'BANK MANDIRI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '9', 'name' => 'BANK BNI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '11', 'name' => 'BANK DANAMON', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '13', 'name' => 'BANK PERMATA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '13', 'name' => 'BANK PERMATA SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '14', 'name' => 'BANK BCA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '16', 'name' => 'BANK MAYBANK (BII)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '19', 'name' => 'BANK PANIN', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '20', 'name' => 'BANK ARTA NIAGA KENCANA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '22', 'name' => 'BANK CIMB NIAGA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '22', 'name' => 'BANK CIMB NIAGA SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '23', 'name' => 'BANK UOB INDONESIA (BANK BUANA INDONESIA)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '23', 'name' => 'BANK UOB INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '26', 'name' => 'BANK LIPPO', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '28', 'name' => 'BANK OCBC NISP', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '30', 'name' => 'AMERICAN EXPRESS BANK LTD', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '31', 'name' => 'CITIBANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '32', 'name' => 'JP. MORGAN CHASE BANK, N.A.', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '33', 'name' => 'BANK OF AMERICA, N.A', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '34', 'name' => 'ING INDONESIA BANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '36', 'name' => 'BANK CCB INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '37', 'name' => 'BANK ARTHA GRAHA INTERNASIONAL', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '39', 'name' => 'BANK CREDIT AGRICOLE INDOSUEZ', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '40', 'name' => 'THE BANGKOK BANK COMP. LTD', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '42', 'name' => 'MUFG BANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '45', 'name' => 'BANK SUMITOMO MITSUI INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '46', 'name' => 'BANK DBS INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '46', 'name' => 'DIGIBANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '47', 'name' => 'BANK RESONA PERDANIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '48', 'name' => 'BANK MIZUHO INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '50', 'name' => 'STANDARD CHARTERED BANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '52', 'name' => 'BANK ABN AMRO', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '53', 'name' => 'BANK KEPPEL TATLEE BUANA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '54', 'name' => 'BANK CAPITAL INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '57', 'name' => 'BANK BNP PARIBAS INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '59', 'name' => 'KOREA EXCHANGE BANK DANAMON', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '60', 'name' => 'RABOBANK INTERNASIONAL INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '61', 'name' => 'BANK ANZ INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '69', 'name' => 'BANK OF CHINA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '76', 'name' => 'BANK BUMI ARTA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '87', 'name' => 'BANK HSBC INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '88', 'name' => 'BANK ANTARDAERAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '89', 'name' => 'BANK HAGA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '93', 'name' => 'BANK IFI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '95', 'name' => 'BANK J TRUST INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '97', 'name' => 'BANK MAYAPADA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '110', 'name' => 'BANK JABAR BJB (JAWA BARAT)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '111', 'name' => 'BANK DKI JAKARTA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '112', 'name' => 'BPD DIY (YOGYAKARTA)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '113', 'name' => 'BANK JATENG (JAWA TENGAH)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '115', 'name' => 'BANK JAMBI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '116', 'name' => 'BANK ACEH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '116', 'name' => 'BANK ACEH SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '117', 'name' => 'BANK SUMUT', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '118', 'name' => 'BANK NAGARI (BANK SUMBAR)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '119', 'name' => 'BANK RIAU KEPRI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '120', 'name' => 'BANK SUMSEL BABEL (SUMATERA SELATAN BANGKA BELITUNG)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '121', 'name' => 'BANK LAMPUNG', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '122', 'name' => 'BANK KALSEL (BANK KALIMANTAN SELATAN)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '123', 'name' => 'BANK KALBAR (BANK KALIMANTAN BARAT)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '124', 'name' => 'BANK KALTIMTARA (BANK KALIMANTAN TIMUR DAN UTARA)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '125', 'name' => 'BANK KALTENG (BANK KALIMANTAN TENGAH)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '126', 'name' => 'BANK SULSELBAR (BANK SULAWESI SELATAN DAN BARAT)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '127', 'name' => 'BANK SULUTGO (BANK SULAWESI UTARA DAN GORONTALO)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '128', 'name' => 'BANK NTB', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '128', 'name' => 'BANK NTB SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '129', 'name' => 'BANK BPD BALI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '130', 'name' => 'BANK NTT', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '131', 'name' => 'BANK MALUKU MALUT', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '132', 'name' => 'BANK PAPUA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '133', 'name' => 'BANK BENGKULU', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '134', 'name' => 'BANK SULTENG (BANK SULAWESI TENGAH)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '135', 'name' => 'BANK SULTRA (BANK SULAWESI TENGGARA)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '137', 'name' => 'BANK BANTEN', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '145', 'name' => 'BANK NUSANTARA PARAHYANGAN', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '146', 'name' => 'BANK SWADESI (BANK OF INDIA INDONESIA)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '147', 'name' => 'BANK MUAMALAT', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '151', 'name' => 'BANK MESTIKA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '152', 'name' => 'BANK SHINHAN INDONESIA (BANK METRO EXPRESS)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '153', 'name' => 'BANK SINARMAS', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '157', 'name' => 'BANK MASPION INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '159', 'name' => 'BANK HAGAKITA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '161', 'name' => 'BANK GANESHA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '162', 'name' => 'BANK WINDU KENTJANA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '164', 'name' => 'BANK ICBC INDONESIA (HALIM INDONESIA BANK)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '166', 'name' => 'BANK HARMONI INTERNATIONAL', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '167', 'name' => 'BANK QNB INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '200', 'name' => 'BANK BTN', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '212', 'name' => 'BANK WOORI SAUDARA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '213', 'name' => 'BANK BTPN', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '213', 'name' => 'JENIUS', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '405', 'name' => 'BANK VICTORIA SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '422', 'name' => 'BANK BRI SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '425', 'name' => 'BANK JABAR BJB SYARIAH (JAWA BARAT)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '426', 'name' => 'BANK MEGA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '427', 'name' => 'BANK BNI SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '441', 'name' => 'BANK BUKOPIN', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '451', 'name' => 'BANK BSI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '459', 'name' => 'BANK BISNIS INTERNASIONAL', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '466', 'name' => 'BANK SRI PARTHA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '472', 'name' => 'BANK JASA JAKARTA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '484', 'name' => 'BANK HANA (KEB HANA BANK)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '485', 'name' => 'BANK MNC', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '490', 'name' => 'BANK YUDHA BHAKTI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '491', 'name' => 'BANK MITRANIAGA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '494', 'name' => 'BANK BRI AGRO', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '498', 'name' => 'BANK SBI INDONESIA (BANK INDOMONEX)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '501', 'name' => 'BANK DIGITAL BCA (BCA DIGITAL)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '503', 'name' => 'BANK NATIONAL NOBU (BANK ALFINDO)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '506', 'name' => 'BANK MEGA SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '513', 'name' => 'BANK INA PERDANA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '517', 'name' => 'BANK PANIN DUBAI SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '520', 'name' => 'PRIMA MASTER BANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '521', 'name' => 'BANK BUKOPIN SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '521', 'name' => 'BANK PERSYARIKATAN INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '523', 'name' => 'BANK SAHABAT SAMPEORNA (BANK DIPO INTERNATIONAL)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '525', 'name' => 'BANK AKITA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '526', 'name' => 'BANK DINAR INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '531', 'name' => 'ANGLOMAS INTERNASIONAL BANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '535', 'name' => 'BANK KESEJAHTERAAN EKONOMI', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '536', 'name' => 'BANK BCA SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '542', 'name' => 'BANK ARTOS INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '547', 'name' => 'BANK BTPN SYARIAH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '548', 'name' => 'BANK MULTIARTA SENTOSA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '553', 'name' => 'BANK MAYORA INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '555', 'name' => 'BANK INDEX SELINDO', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '558', 'name' => 'BANK EKSEKUTIF', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '559', 'name' => 'CENTRATAMA NASIONAL BANK', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '562', 'name' => 'BANK FAMA INTERNASIONAL', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '564', 'name' => 'BANK MANDIRI TASPEN POS (BANK SINAR HARAPAN BALI)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '566', 'name' => 'BANK VICTORIA INTERNATIONAL', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '567', 'name' => 'BANK HARDA INTERNASIONAL', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '688', 'name' => 'BPR KS (KARYAJATNIKA SEDAYA)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '789', 'name' => 'INDOSAT DOMPETKU', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '911', 'name' => 'TELKOMSEL TCASH', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '911', 'name' => 'LINKAJA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '945', 'name' => 'IBK BANK INDONESIA', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '946', 'name' => 'BANK MERINCORP', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '947', 'name' => 'BANK MAYBANK INDOCORP', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '949', 'name' => 'BANK CTBC INDONESIA (CHINA TRUST)', 'currency_id' => '1', 'is_debt' => '0']);
        Bank::create(['code' => '950', 'name' => 'BANK COMMONWEALTH', 'currency_id' => '1', 'is_debt' => '0']);
    }
}
